CREATE TABLE Salarii(
	ID int PRIMARY KEY IDENTITY(1,1), 
	NUME VARCHAR(50), 
	PRENUME VARCHAR(50), 
	FUNCTIE VARCHAR(50), 
	SALARIU_BAZA NUMERIC(10,2),
	SPOR NUMERIC(10,2),
	PREMII_BRUTE NUMERIC(10,2),
	TOTAL_BRUT NUMERIC(10,2),
	BRUT_IMPOZABIL NUMERIC(10,2),
	IMPOZIT NUMERIC(5,2),
	CAS NUMERIC(5,2),
	CASS NUMERIC(5,2),
	RETINERI NUMERIC(10,2),
	VIRAT_CARD NUMERIC(10,2)
)
