USE [Student];

CREATE TABLE Salarii(
	ID int PRIMARY KEY IDENTITY(1,1), 
	NUME VARCHAR(50), 
	PRENUME VARCHAR(50), 
	FUNCTIE VARCHAR(50), 
	SALARIU_BAZA INT,
	SPOR INT,
	PREMII_BRUTE INT,
	TOTAL_BRUT INT,
	BRUT_IMPOZABIL INT,
	IMPOZIT INT,
	CAS INT,
	CASS INT,
	RETINERI INT,
	VIRAT_CARD INT
)
